# Default Spring Boot Properties
spring.profiles.active=dev

# Application Identity
spring.application.name=employee-management-system

# Swagger & Springdoc Config
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html